name: Gunluk YDS Kelime Botu

on:
  schedule:
    # Her gün Türkiye saati ile sabah 08:00'de çalışır (UTC 05:00)
    - cron: '0 5 * * *'
  workflow_dispatch: # İstediğin zaman manuel tetiklemek için

permissions:
  contents: write

# Node.js 20 uyarılarını tamamen kapatmak ve Node 24'ü zorlamak için çevresel değişken ekliyoruz
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-word:
    runs-on: ubuntu-latest
    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Kelimeyi Güncelle
      run: python update_word.py

    - name: GitHub'a Commit Et ve Gönder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "hafizecim"
        git add Gunun_Kelimesi.md
        git commit -m "Daily YDS Word Update: $(date +'%Y-%m-%d')" || exit 0
        git push
